[worker]
name = "<WORKER_NAME>"
# rpc_server.host = "192.168.1.100"
# rpc_server.port = 17891

local_pieces_dir = '/data/pieces/'

# [metrics]

[sector_manager]
rpc_client.addr = "/dns/vsm/tcp/1789"


[sealing]
enable_deals = true
max_retries = 3

[[sealing_thread]]
location = "/data/<WORKER_NAME>/store/store1"


[[sealing_thread]]
location = "/data/<WORKER_NAME>/store/store2"


[[sealing_thread]]
location = "/data/<WORKER_NAME>/store/store3"


[[attached]]
name = "persist-store"
location = "/data/persist/"

[processors.limitation.concurrent]
