[worker]
name = "worker1"
# rpc_server.host = "192.168.1.100"
# rpc_server.port = 17891

# [metrics]

[sector_manager]
rpc_client.addr = "/dns/vsm/tcp/1789"


[sealing]
enable_deals = true
max_retries = 3

[[sealing_thread]]
location = "/data/store/store1"


[[sealing_thread]]
location = "/data/store/store2"


[[sealing_thread]]
location = "/data/store/store3"


[[attached]]
name = "persist-store"
location = "/data/pieces/"

[processors.limitation.concurrent]
